### ISSUE TITLE
Adopt config connector GKE addon or operator?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#148]
Part of https://github.com/kubeflow/gcp-blueprints/issues/139

https://cloud.google.com/config-connector/docs/concepts/installation-types
Config connector is only documenting GKE addon or operator solutions now, so I think we should switch to one of them

It says the GKE addon has a relatively old version, but I just checked an installation. It's not that old, right now it's config connector `1.23.0`. That's much newer than what we had in Kubeflow 1.1 as `1.9.0`.

/cc @jlewi

**Comment by Bobgy** [comment]
FWIW, the GKE addon installed version has this config
```
- apiVersion: core.cnrm.cloud.google.com/v1beta1
  kind: ConfigConnector
  metadata:
    creationTimestamp: "2020-11-05T08:33:23Z"
    finalizers:
    - configconnector.cnrm.cloud.google.com/finalizer
    generation: 3
    name: configconnector.core.cnrm.cloud.google.com
    resourceVersion: "1646"
    selfLink: /apis/core.cnrm.cloud.google.com/v1beta1/configconnectors/configconnector.core.cnrm.cloud.google.com
    uid: 37e96dba-d1da-4a8f-8368-acf05b09cf24
  spec:
    mode: namespaced
  status:
    healthy: true
```

**Comment by Bobgy** [comment]
Reading the entire documentation, it seems GKE addon has the best support.
Installing it is just enabling an addon, upgrade will happen automatically with GKE upgrade.

**Comment by Bobgy** [comment]
The remaining question is how can we upgrade users from config connector 1.9.0 to GKE addon.

**Comment by Bobgy** [comment]
I just tried enabling the GKE addon on an existing cluster:
```
gcloud container clusters update CLUSTER_NAME --update-addons ConfigConnector=ENABLED
```

It correctly take control of `cnrm-system` namespace, we'll need to edit the conofigconnector resource as usual like
```
# configconnector.yaml
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one
  # ConfigConnector instance installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
spec:
 mode: cluster
 googleServiceAccount: "SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com"
```
