### ISSUE TITLE
Profile deployment: configmap kubeflow-config not found

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#24]
There are usages of the configmap like
```
env:
        - name: USERID_HEADER
          valueFrom:
            configMapKeyRef:
              key: userid-header
              name: kubeflow-config
```

However, kubeflow-config is generated by configmap-generator, it should have a suffix. Not sure exact why, but kustomize didn't append the suffix to profile deployment.

Reproduced with kustomize version 3.1.0. (I cannot use kustomize 3.5.4 to test, there were another error)
