### ISSUE TITLE
Failed creating kubeflow cluster because VPC is not identified

### ISSUE THREAD

**Issue by sidiksoleman** [kubeflow/gcp-blueprints#337]
We used VPC for our gcp project. Thus, we modified the cluster.yaml for both management cluster and kubeflow cluster. 

In management cluster, we add two specification, i.e. 
network: <name of vpc network>
subnetwork: <name of vpc subnetwork>

I tried to use the specification here: https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster#vpc_native_container_cluster, but it is not working for deploying management cluster. While the above one is working well and the management cluster was successfully deployed. 

However, when I use the same yaml format for deploying kubeflow cluster, the above format cannot be recognized. Thus, I used the format from GCP, i.e.
networkRef:
   name: <name of vpc network>
subnetworkRef:
  name: <name of vpc subnetwork>
But, I encountered another problem, i.e. ComputerNetwork is not found. 

Did I miss something? Why we can successfully deployed management cluster using different format than the one mentioned in the GCP page. However, although the format is correct, but why it cannot find the VPC while it was not a problem while deploying management cluster. 

Thank you. 

Kubeflow version: 1.4.0
OS: ubuntu 18.04
Google Cloud SDK: 366.0.0
beta: 2021.12.03
bq: 2.0.72
core: 2021.12.03
gsutil: 5.5
kpt: 1.0.0-beta.7
kubectl: 1.20.8
kustomize: 4.4.0

**Comment by zijianjoy** [comment]
Hello @sidiksoleman , we currently do not support VPC with Kubeflow cluster. Welcome contribution if you find out the solution.

**Comment by schrodervictor** [comment]
It seems this is still open. After successfully creating the management cluster, I wanted to deploy the managed kubeflow cluster in a VPC (`network`) and subnet (`subnetwork`) that I had previously created in my project. It didn't work.

It turns out that `networkRef.name` and `subnetworkRef.name` only work for resources managed by the Config Connector (the `name` they expect are the respective proxy k8s resources). To reference a network and subnetwork _not managed_ by Config Connector, we need to use `networkRef.external` and `subnetworkRef.external`, pointing to the fully qualified URL that identifies the target resources. Example:

```yaml
# kubeflow/common/cluster/upstream/cluster.yaml
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  ...
spec:
  ...
  networkRef:
    external: https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/global/networks/${NETWORK_NAME}
  subnetworkRef:
    external: https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/regions/${REGION_NAME}/subnetworks/${SUBNETWORK_NAME}
```
